/* ============================================================
   VIRTUAL FILE SYSTEM — 50+ Interconnected Lore Files
   Project 713: The Nedry Audit
   ============================================================ */

const VFS = (() => {
    // File types
    const DIR = 'dir';
    const FILE = 'file';

    // Evidence flags
    const EVIDENCE = {
        LYSINE: 'lysine_failure',
        BREEDING: 'breeding_evidence',
        SITE_B: 'site_b_location',
        BACKDOOR: 'nedry_backdoor',
        BIOSYN: 'biosyn_deal'
    };

    // Build the tree
    const fs = {
        type: DIR, children: {
            sys: { type: DIR, children: {
                park: { type: DIR, children: {
                    Control: { type: DIR, children: {
                        'tour_program.vax': { type: FILE, modified: '06/01/1993 10:00', size: '12.4K', content:
`TOUR PROGRAM — JURASSIC PARK
Version: 2.1.4
Author: D. Nedry (InGen Systems)

Module: Automated Tour Vehicle Control
Status: OPERATIONAL (pending update)

This program controls the electric rail-guided
Explorer vehicles along the 32-mile tour route.

Route Checkpoints:
  01 — Main Gate
  02 — Dilophosaurus Paddock
  03 — Triceratops Paddock
  04 — T-Rex Paddock (Speed limit enforced)
  05 — Brachiosaur Lake
  06 — Gallimimus Run
  07 — Return to Visitor Center

NOTE: Nedry has not delivered the v2.2 update.
The system still runs on the original GPS module
which has a ±3m drift in heavy rain.` }
                    }},
                    Fences: { type: DIR, children: {
                        'perimeter_fence_control.sys': { type: FILE, modified: '06/11/1993 22:00', size: '8.1K', content:
`PERIMETER FENCE CONTROL SYSTEM
Version: 3.0.1 | InGen Security Division

CIRCUIT MAP:
  Circuit 01-A..D — Visitor Area (2,000V)
  Circuit 02-A..D — Herbivore North (5,000V)
  Circuit 03-A..D — Herbivore South (5,000V)
  Circuit 04-A..D — Dilophosaurus (7,500V)
  Circuit 05-A..D — Gallimimus (5,000V)
  Circuit 06-A..D — Stegosaurus (3,000V)
  Circuit 07-A..D — Raptor (10,000V) *MAXIMUM*
  Circuit 08-A..D — T-Rex (10,000V) *MAXIMUM*

OVERRIDE CAPABILITY:
  Individual circuits can be disabled from
  the main control terminal (NEDRY-WS01).
  
  WARNING: Emergency override disables ALL
  circuits simultaneously. This is by design
  per J. Hammond's directive to facilitate
  emergency evacuations.
  
  NOTE: There is no selective emergency mode.
  It's all or nothing. — R. Arnold` }
                    }},
                    Power: { type: DIR, children: {
                        'main_grid.sys': { type: FILE, modified: '06/11/1993 18:00', size: '3.2K', content:
`MAIN POWER GRID — ISLA NUBLAR
Status: OPERATIONAL
Primary Source: Geothermal Plant (East Ridge)
Backup: Diesel Generator Farm (x3)

Grid Load: 68% capacity
Peak Load (June avg): 74%

CRITICAL SYSTEMS (Uninterruptible):
  - Perimeter Fences
  - Embryo Cold Storage
  - Security Cameras
  - Communications Array
  - Control Room

NON-CRITICAL (Shed-able):
  - Visitor Center Lighting
  - Tour Vehicle Rail
  - HVAC (non-server)
  - Landscape Irrigation

Transfer Switch Status:
  Gen #01: 4.2s (PASS)
  Gen #02: 6.1s (PASS)
  Gen #03: 12.2s (FAIL — exceeds 8s spec)` }
                    }},
                    'park_scheduler.dat': { type: FILE, modified: '06/11/1993 08:00', size: '12K', content:
`JURASSIC PARK — DAILY OPERATIONS SCHEDULE
Date: 06/11/1993 (Saturday)
Generated by: Central Operations System
═════════════════════════════════════

06:00  Morning feeding — all herbivore paddocks
07:00  Security shift change (Night → Day)
07:30  Perimeter fence voltage check
08:00  Veterinary rounds (Dr. Harding)
09:00  Visitor center prep
10:00  Tour departure #1 (2 Explorers, 6 guests)
12:00  Midday feeding — carnivore paddocks
13:00  Tour departure #2
14:00  Maintenance window (Sectors 5-8)
16:00  Evening feeding — all paddocks
18:00  Security shift change (Day → Night)
19:00  Perimeter sweep (motion sensor check)
20:00  Generator test cycle
21:00  Night operations begin
22:00  Dock resupply (if scheduled)

NOTE: Sunday 06/12 — full inspection day.
      All systems to be checked before Monday
      investor presentation.` },
                    'asset_tags.db': { type: FILE, modified: '06/10/1993 16:00', size: '3.2K', content:
`INGEN ASSET TAG DATABASE
Last Updated: 06/10/1993
═════════════════════════════════════

Tag     Species              Paddock  Status
─────────────────────────────────────────
#001    T. Rex               P01     CONTAINED
#002    T. Rex (juvenile)    P01     CONTAINED
#003    Velociraptor          P12     CONTAINED
#004    Velociraptor          P12     CONTAINED
#005    Velociraptor          P12     CONTAINED
#006    Triceratops          P03     ILL
#007    Triceratops          P03     CONTAINED
#008    Brachiosaurus        P02     CONTAINED
#009    Brachiosaurus        P02     CONTAINED
#010    Dilophosaurus        P04     CONTAINED
#011    Stegosaurus          P06     CONTAINED
#012    Gallimimus (flock)   P05     CONTAINED
#013    Parasaurolophus      P09     CONTAINED
#014    Compsognathus (pod)  P08     LOOSE

Total Tagged: 238
Total Tracked: 292 (!!!)

>>> DISCREPANCY: 54 UNTAGGED ANIMALS <<<
>>> See: /lab/genetics/breeding_report_06.log` },
                    maint: { type: DIR, children: {
                        'EXP_9_SENSOR.LOG': { type: FILE, modified: '06/11/1993 14:22', size: '4.2K', content:
`================================================================
  JURASSIC PARK — MAINTENANCE TICKET #4471
  ASSET: Explorer Vehicle 09
  LOCATION: Paddock 4 (Dilophosaurus Enclosure)
  DATE: 06/11/1993  TECH: R. Martinez
================================================================

ISSUE: Proximity Sensor Failure — Intermittent False Positives

DESCRIPTION:
  Explorer 09 has logged 14 "Ghost Obstacle" events over the
  past 48 hours while the vehicle was STATIONARY in the
  maintenance bay adjacent to Paddock 4.

SENSOR LOG EXTRACT:
  [06/10 02:14:08] PROX_ALERT: Object detected — 0.8m — FRONT
  [06/10 02:14:09] PROX_ALERT: Object cleared
  [06/10 02:17:33] PROX_ALERT: Object detected — 0.6m — FRONT
  [06/10 02:17:34] PROX_ALERT: Object detected — 0.4m — FRONT
  [06/10 02:17:35] PROX_ALERT: Object cleared
  [06/10 03:45:12] PROX_ALERT: Object detected — 1.2m — LEFT
  [06/10 03:45:12] PROX_ALERT: Object cleared
  [06/10 03:45:13] PROX_ALERT: Object detected — 0.3m — LEFT
  ...
  [TOTAL GHOST OBSTACLES: 14]

DIAGNOSIS:
  Sensor hardware tested — PASS. Wiring tested — PASS.
  All 14 events occurred between 0200h-0500h.
  No maintenance personnel present during those hours.

  NOTE: Maintenance bay shares a fence line with Paddock 4.
  Recommend checking if wildlife is triggering the sensors
  through the fence mesh.

  >>> AMENDED NOTE (R. Arnold): "Wildlife" doesn't stand
  still for two minutes at a time. Check the Dilophosaur
  activity logs — they've been observed standing motionless
  near the fence for extended periods. Hunting behavior?
  Motion sensors wouldn't flag a stationary animal. The
  proximity sensors did. Think about that.

STATUS: UNRESOLVED — Awaiting further analysis
================================================================` },

                        'GRID_STABILITY_07.LOG': { type: FILE, modified: '06/11/1993 09:15', size: '3.8K', content:
`================================================================
  JURASSIC PARK — POWER GRID STABILITY REPORT
  SECTOR: 07 (Raptor Containment)
  PERIOD: 06/01/1993 — 06/11/1993
  ENGINEER: R. Arnold
================================================================

ANOMALY: Intermittent voltage drops detected on perimeter
fence Circuit 07-A through 07-D.

VOLTAGE LOG (Nominal: 10,000V):
  Date       Time      Circuit   Reading   Drop
  ─────────────────────────────────────────────────
  06/02      04:12:08  07-B      9,999.5V  0.5V
  06/03      04:08:33  07-C      9,999.5V  0.5V
  06/04      04:15:01  07-B      9,999.4V  0.6V
  06/05      04:11:47  07-A      9,999.5V  0.5V
  06/06      04:09:22  07-D      9,999.5V  0.5V
  06/07      04:14:55  07-B      9,999.5V  0.5V
  06/08      04:12:11  07-C      9,999.4V  0.6V
  06/09      04:10:38  07-A      9,999.5V  0.5V
  06/10      04:13:29  07-B      9,999.5V  0.5V
  06/11      04:11:02  07-D      9,999.5V  0.5V

ANALYSIS:
  Drops are consistent at 0.5V and occur exclusively
  between 0400h-0415h. Pattern suggests a systematic
  external load being briefly applied to the fence.

  INITIAL ASSESSMENT: Minor grounding issues. Possibly
  moisture on insulator posts during early morning
  dew accumulation.

  >>> PERSONAL NOTE (R. Arnold):
  I don't like this. The drops cycle through ALL FOUR
  circuits sequentially. That's not moisture. That's
  something testing each section of fence in order.
  Every night. Same time. They're learning the cycle.

  Mentioned this to Muldoon. He didn't seem surprised.
  Said he's been saying it for months. Nobody listens.

STATUS: Monitoring — No action taken per Hammond directive
================================================================` },

                        'HVAC_CONTROL_ROOM.LOG': { type: FILE, modified: '06/10/1993 16:30', size: '1.2K', content:
`HVAC SYSTEM — CONTROL ROOM
Status: NOMINAL
Temp: 68°F (20°C) | Humidity: 45%
Server Rack Cooling: ACTIVE
NOTE: Compressor #2 showing early wear.
Parts on order — ETA 3 weeks from San José.
Nedry complained about temperature again.
Set his terminal zone to 66°F per request.` },

                        'TOUR_VEHICLE_MAINT.LOG': { type: FILE, modified: '06/09/1993 11:00', size: '1.8K', content:
`TOUR VEHICLE MAINTENANCE SCHEDULE
══════════════════════════════════
Vehicle  Status      Last Service  Next Due    Notes
───────────────────────────────────────────────────────
EXP-01   ACTIVE      06/01/1993    07/01/1993  OK
EXP-02   ACTIVE      06/01/1993    07/01/1993  OK
EXP-03   ACTIVE      05/28/1993    06/28/1993  OK
EXP-04   ACTIVE      06/05/1993    07/05/1993  OK
EXP-05   ACTIVE      06/03/1993    07/03/1993  Tire wear
EXP-06   RESERVE     05/15/1993    —           GPS offline
EXP-07   ACTIVE      06/07/1993    07/07/1993  OK
EXP-08   ACTIVE      06/02/1993    07/02/1993  OK
EXP-09   MAINTENANCE 06/11/1993    —           See #4471
EXP-10   RESERVE     04/20/1993    —           Paint damage

Track rail lubrication: Due 06/15/1993
Tour program software: v2.1.4 — Update pending (Nedry)` },

                        'GENERATOR_03.LOG': { type: FILE, modified: '06/10/1993 22:14', size: '1.1K', content:
`GENERATOR #03 — BACKUP POWER UNIT
Location: East Maintenance Compound
Fuel Level: 78%
Last Test Run: 06/08/1993 — PASS
Auto-Start: ENABLED

WARNING: Transfer switch response time measured
at 12.2 seconds. Spec requires <8 seconds.
Recommend immediate maintenance.

NOTE (Arnold): If main power goes down, there
will be a 12-second window where NOTHING is
electrified. Hammond says the animals won't
notice. Hammond hasn't met the raptors.`
                        }
                    }},
                    sec: { type: DIR, children: {
                        'RAP_01_DYNAMICS.TXT': { type: FILE, modified: '06/10/1993 19:45', size: '5.1K', content:
`================================================================
  JURASSIC PARK — BEHAVIORAL OBSERVATION LOG
  SUBJECT: Velociraptor Pack — Paddock 12
  OBSERVER: R. Muldoon, Park Warden
  CLASSIFICATION: *** RESTRICTED ***
================================================================

SUBJECT DESIGNATION: "The Big One"
  Species: Velociraptor antirrhopus nublarensis
  Sex: Female | Est. Weight: 150kg | Length: 3.8m
  Acquired: 02/1993 from Site B batch VR-08

BEHAVIORAL OBSERVATIONS — JUNE 1993:

06/03: The Big One killed subordinate VR-12 today.
  Third kill this quarter. She didn't eat any of it.
  Wu says it's "dominance behavior." It isn't.
  She killed VR-12 directly in front of Camera 4.
  While we were all watching the monitors, VR-09
  was testing the fence at the feed gate.
  It was a distraction.

06/05: They've changed their feeding pattern. Used
  to rush the gate when the feeders came. Now they
  stay back. Watch. Wait. Then one approaches from
  the side while two others position at the rear.
  They're not hunting the cow. They're studying
  the gate mechanism.

06/08: Requested AGAIN that we install redundant
  locks on all raptor enclosure gates. Hammond
  denied — "too expensive, too ugly for the tour."
  Filed formal objection.

06/09: I've watched the tapes. When the cameras pan
  away from the fence line (every 90 seconds on the
  automated sweep), The Big One approaches the fence.
  She's timed the camera rotation.

06/10: The Big One has started making a new call.
  Low, rhythmic. The others respond differently to
  it than to her hunting calls. I think she's
  giving orders.

  Recommendation: Destroy all animals in Paddock 12
  and start over with a new batch. They are too
  intelligent and too coordinated.

  Response from Hammond: "These animals are worth
  more than you are, Robert."

  God help us all.
================================================================` },

                        'CAM_LOOP_SOURCE.C': { type: FILE, modified: '06/12/1993 01:34', size: '2.3K', evidence: EVIDENCE.BACKDOOR, content:
`/* ================================================
 * cam_loop.c — Security Camera Feed Override
 * Found in: /usr/nedry/bin/
 * Last Modified: 06/12/1993 01:34
 * ================================================
 * THIS CODE WAS FOUND ON NEDRY'S WORKSTATION
 * It feeds a 3-minute recorded loop to security
 * monitors, masking real-time camera feeds.
 * ================================================ */

#include <stdio.h>
#include <security/cam_api.h>
#include <time.h>

#define LOOP_DURATION_SEC  180  /* 3 minutes */
#define BUFFER_FRAMES      5400 /* 30fps * 180s */

static frame_t loop_buffer[BUFFER_FRAMES];
static int loop_active = 0;

int init_cam_loop(int cam_id) {
    /* Record 3 minutes of "normal" footage */
    printf("Recording baseline... ");
    for (int i = 0; i < BUFFER_FRAMES; i++) {
        loop_buffer[i] = cam_capture(cam_id);
        usleep(33333); /* ~30fps */
    }
    printf("Done.\\n");
    return 0;
}

int activate_loop(int cam_id) {
    loop_active = 1;
    int frame = 0;
    while (loop_active) {
        cam_override_feed(cam_id, loop_buffer[frame]);
        frame = (frame + 1) % BUFFER_FRAMES;
        usleep(33333);
    }
    return 0;
}

/* Called from whiterabbit.exe */
void nedry_cam_bypass(void) {
    int cams[] = {1, 2, 3, 5, 7, 8, 12};
    for (int i = 0; i < 7; i++) {
        init_cam_loop(cams[i]);
        activate_loop(cams[i]);
    }
    /* Cameras 4, 6, 9, 10, 11 left active */
    /* — nobody watches those sectors anyway */
}` },

                        'PERIMETER_BREACH_LOG.TXT': { type: FILE, modified: '06/12/1993 03:15', size: '1.4K', content:
`PERIMETER SECURITY — BREACH EVENTS
════════════════════════════════════
Date       Time     Sector  Type          Status
──────────────────────────────────────────────────
06/12/93   00:15    EAST    Motion Alert  FALSE ALARM
06/12/93   01:48    DOCK    Gate Open     AUTHORIZED (Nedry)
06/12/93   02:01    DOCK    Gate Open     UNAUTHORIZED
06/12/93   02:04    SOUTH   Fence Alarm   SYSTEM OFFLINE
06/12/93   02:04    ALL     Fence Alarm   SYSTEM OFFLINE

WARNING: Mass fence failure detected at 02:04.
  All perimeter systems went offline simultaneously.
  Cause: Unknown — power grid shows active.
  Security override code detected in system log.
  Override origin: Terminal NEDRY-WS01` },

                        'MOTION_SENSOR_GRID.DAT': { type: FILE, modified: '06/11/1993 23:59', size: '0.8K', content:
`MOTION SENSOR GRID — COVERAGE MAP
Sectors: 24 active / 3 offline / 1 maintenance
Total sensors: 340
Active coverage: 92%

OFFLINE SECTORS:
  Sector 14 — East dock approach (sensor #221-228)
    Status: Disabled by Nedry 06/10/93
    Reason: "Calibration maintenance"
  Sector 19 — North perimeter (sensor #301-308)
    Status: Disabled by Nedry 06/10/93
    Reason: "False positive reduction"
  Sector 22 — Embryo storage approach (sensor #330-340)
    Status: Disabled by Nedry 06/11/93
    Reason: "Hardware failure"

NOTE: All three disabled sectors form a clear
path from the Control Room to the East Dock.`
                        }
                    }},
                }},
                logs: { type: DIR, children: {
                    raw: { type: DIR, children: {
                        'SENSE_COUNT.DAT': { type: FILE, modified: '06/12/1993 00:00', size: '0.4K', content:
`ISLA NUBLAR — RAW SENSOR TELEMETRY
════════════════════════════════════
Automated Census (Motion + Thermal + Visual)
Timestamp: 06/12/1993 00:00:00

SENSE_COUNT=292

Raw sensor hits by sector:
  Paddock 01 (T-Rex):        1
  Paddock 02 (Brachiosaur):  7
  Paddock 03 (Triceratops):  4
  Paddock 04 (Dilophosaur):  8
  Paddock 05 (Gallimimus):  37
  Paddock 06 (Parasaurolophus): 12
  Paddock 07 (Stegosaurus):  6
  Paddock 08 (Compy):       49
  Paddock 09 (Pteranodon):  14
  Paddock 10 (Herrerasaur):  3
  Paddock 11 (Othnielia):   28
  Paddock 12 (Raptor):       8
  Free-Range/Uncontained:  115

TOTAL: 292

WARNING: Free-range count 115 exceeds manifest
total of 238. Unaccounted specimens detected.` },
                    }},
                    'park_status.exe': { type: FILE, modified: '06/11/1993 22:00', size: '1.8K', content:
`/* park_status.exe — Decompiled output
 * InGen Park Management System v2.3
 * Modified by: D. Nedry (06/02/1993)
 * ──────────────────────────────────── */

int get_animal_count(void) {
    int count = raw_sensor_count();
    int expected = manifest_count(); /* 238 */

    /* NEDRY MODIFICATION — 06/02/1993 */
    if (count > expected) {
        count = expected;
    }
    /* END MODIFICATION */

    return count;
}

/* Original code (commented out by Nedry):
 *
 * int get_animal_count(void) {
 *     int count = raw_sensor_count();
 *     if (count != manifest_count()) {
 *         trigger_alert(ALERT_CENSUS_MISMATCH);
 *         log_event("Census discrepancy detected");
 *     }
 *     return count;
 * }
 */` },
                    'access_log.dat': { type: FILE, modified: '06/12/1993 02:30', size: '2.1K', content:
`ACCESS LOG — NEDRY-WS01
════════════════════════
Date       Time     Action                    Duration
──────────────────────────────────────────────────────
06/02/93   23:14    Login:nedry               —
06/02/93   23:16    Modified: park_status.exe  4m
06/02/93   23:22    Accessed: /sys/root       DENIED
06/02/93   23:23    Logout:nedry              —
06/05/93   01:02    Login:nedry               —
06/05/93   01:04    Compiled: cam_loop.c       8m
06/05/93   01:15    Compiled: whiterabbit.obj  12m
06/05/93   01:30    Logout:nedry              —
06/08/93   22:45    Login:nedry               —
06/08/93   22:47    Disabled: Sensor Sec.14    1m
06/08/93   22:50    Disabled: Sensor Sec.19    1m
06/08/93   22:53    Logout:nedry              —
06/10/93   23:30    Login:nedry               —
06/10/93   23:32    Disabled: Sensor Sec.22    1m
06/10/93   23:35    Test: whiterabbit.obj      5m
06/10/93   23:42    Logout:nedry              —
06/12/93   00:30    Login:nedry               —
06/12/93   00:32    Execute: whiterabbit.obj   —
06/12/93   00:33    Cam Override: ACTIVE       —
06/12/93   00:34    Security: DISABLED         —
06/12/93   00:35    Fences: DISABLED           —
06/12/93   00:36    Embryo Cold Storage: OPEN  —
06/12/93   00:40    East Dock Gate: OPEN       —
06/12/93   00:45    Session: ABANDONED         —

NOTE: Session 06/12 00:30 was never logged out.
Terminal found still active by R. Arnold at 04:15.` },

                    /* ─────── SHIPPING / DOCK MANIFESTS ─────── */
                    Shipping: { type: DIR, children: {
                        'dock_manifest_06.txt': { type: FILE, modified: '06/10/1993 08:00', size: '1.5K', content:
`EAST DOCK — SUPPLY MANIFEST
Month: June 1993
Dock Master: T. Williams
═════════════════════════════════════
INCOMING SHIPMENTS:

06/02  M/V Isla Bonita
  - 2,000kg Frozen Beef (Livestock Ops)
  - 500kg Fish (Pteranodon feed)
  - Generator Parts (Maint. Dept)
  - 4x Crates: Lab Supplies (Dr. Wu)
  - 1x Industrial Refrigerant (Embryo Storage)

06/06  M/V Anne B
  - 15 Live Goats (T-Rex paddock)
  - 800kg Chicken (Dilophosaurus)
  - 3x Bags Lysine Supplement (100kg ea)
  - Medical Supplies (Dr. Harding)

06/09  M/V Isla Bonita (return)
  - 2,500kg Frozen Beef
  - Construction Materials (Visitor Center)
  - Personal Mail Delivery (staff)
  - 1x Crate: CLASSIFIED (A. Sorna — Site B?)

OUTGOING:
  06/04  Waste Removal (biohazard)
  06/08  Staff Rotation (4 personnel)

SCHEDULED: 
  06/13  M/V Isla Bonita — REGULAR SUPPLY RUN
  06/13  SPECIAL: Inspection boat (Hammond + guests)

NOTE: Night dock access restricted after
incident 05/15. Guard rotation: 00:00 — 00:18
(shift change gap remains unresolved).` },

                        'cargo_inventory.txt': { type: FILE, modified: '06/11/1993 14:00', size: '0.8K', content:
`EAST DOCK — CARGO WAREHOUSE INVENTORY
As of: 06/11/1993
═════════════════════════════════════
Bay 1: Frozen Storage
  - Beef: 1,200kg (3 day supply)
  - Chicken: 400kg (2 week supply)
  - Fish: 300kg (1 week supply)

Bay 2: Dry Storage
  - Lysine Supplement: 250kg
  - Feed Pellets: 800kg
  - Veterinary Supplies: 4 crates

Bay 3: Equipment
  - Generator Parts: 2 pallets
  - Fence Repair Kit: 1
  - Explorer Vehicle Parts: miscellaneous
  - Barbasol Shaving Cream: 1 (Lost & Found)

Bay 4: RESTRICTED
  - Lab Reagents (Class III Biohazard)
  - Amber Specimens (6 units, sealed)
  - Embryo Transport Container (empty)

>> Bay 4 access requires Level 3+ clearance` }
                    }},

                    /* ─────── HR / PERSONNEL ─────── */
                    HR: { type: DIR, children: {
                        'nedry_employee_file.txt': { type: FILE, modified: '01/15/1993 10:00', size: '1.2K', content:
`INTERNATIONAL GENETIC TECHNOLOGIES, INC.
EMPLOYEE RECORD — CONFIDENTIAL
═════════════════════════════════════
Name: NEDRY, Dennis T.
Employee ID: ING-0147
Position: Lead Systems Programmer
Department: Information Technology
Location: Isla Nublar / Remote
Hire Date: 09/01/1991
Contract Type: Fixed-Term (2 years)

Education:
  B.S. Computer Science — Cambridge (1984)
  M.S. Computer Science — MIT (1986)

Contract Value: $150,000 (2-year term)
  >> DISPUTE FILED: 03/10/1993
  >> Employee claims scope exceeded contract
  >> Status: UNDER REVIEW (Legal Dept)

Clearance Level: 3 (System Admin)
Access: All park systems, server room,
  control room. NO embryo lab access.

Emergency Contact: Margaret Nedry (mother)
  Phone: 212-555-0188

Performance Reviews:
  1992-Q1: EXCEEDS EXPECTATIONS
  1992-Q2: MEETS EXPECTATIONS
  1992-Q3: MEETS EXPECTATIONS
  1992-Q4: BELOW EXPECTATIONS (attitude)
  1993-Q1: BELOW EXPECTATIONS (dispute)

Notes: Employee has filed formal grievance
regarding compensation. Handle with care.
— HR Director` },

                        'safety_training.txt': { type: FILE, modified: '03/01/1993 09:00', size: '0.7K', content:
`STAFF SAFETY TRAINING — COMPLETION RECORD
═════════════════════════════════════
Employee: NEDRY, Dennis T.
ID: ING-0147

Course                        Status    Date
────────────────────────────  ────────  ──────
Dinosaur Awareness 101        PASSED    09/15/91
Emergency Evacuation Proc.    PASSED    09/15/91
Biohazard Handling            PASSED    10/01/91
Electric Fence Safety         PASSED    10/01/91
Server Room Protocols         PASSED    09/20/91
First Aid / CPR               EXPIRED   09/15/92
Raptor Proximity Warning      SKIPPED   —
Storm Shelter Procedures      SKIPPED   —

>> 2 REQUIRED COURSES INCOMPLETE <<
>> Employee repeatedly fails to schedule
>> remaining certifications.
>> Last reminder sent: 02/28/1993
>> No response received.` }
                    }}
                }},
                root: { type: DIR, locked: true, bypass: '7091', children: {
                    'MASTER_SHUTDOWN.SH': { type: FILE, modified: '01/15/1993 08:00', size: '0.6K', content:
`#!/bin/sh
# MASTER SYSTEM SHUTDOWN — EMERGENCY USE ONLY
# Authorization: Level 5 (Hammond/Arnold)
#
# WARNING: This will shut down ALL park systems
# including perimeter fences.
#
# To restart: Physical access to the maintenance
# shed breaker panel is required.
#
# "Mr. Arnold, when Disneyland opened in 1953,
#  nothing worked." — J. Hammond
#
# "Yeah, but John, when Pirates of the Caribbean
#  breaks down, the pirates don't eat the tourists."
#  — I. Malcolm

shutdown -h now --force --all-systems` },
                    'EMBRYO_MANIFEST.DAT': { type: FILE, modified: '06/11/1993 20:00', size: '1.2K', content:
`EMBRYO COLD STORAGE — COMPLETE MANIFEST
════════════════════════════════════════
Cryo Unit: Alpha-7 | Temp: -20°C | Status: SECURE

Species             Viable  Non-Viable  Total
────────────────────────────────────────────────
Tyrannosaurus Rex      2        1          3
Velociraptor           8        3         11
Triceratops            4        2          6
Brachiosaurus          3        1          4
Dilophosaurus          6        2          8
Stegosaurus            3        0          3
Gallimimus             5        2          7
Parasaurolophus        4        1          5
Pteranodon             4        3          7
Compsognathus         12        5         17
────────────────────────────────────────────────
TOTAL                 51       20         71

ESTIMATED BLACK MARKET VALUE: $1,450,000,000
(Per BioSyn internal assessment — INTERCEPTED)

NOTE: Nedry only needs 15 viable embryos to
fulfill Dodgson's order. Barbasol can modified
to hold exactly that number.` }
                }}
            }},
            lab: { type: DIR, children: {
                med: { type: DIR, children: {
                    assets: { type: DIR, children: {
                        'TRL_01_BLOOD_WORK.TAB': { type: FILE, modified: '06/10/1993 14:30', size: '3.6K', evidence: EVIDENCE.LYSINE, content:
`================================================================
  JURASSIC PARK — VETERINARY BLOOD WORK ANALYSIS
  SUBJECT: Tyrannosaur 01 (Rexy)
  VET: Dr. G. Harding
  DATE: 06/10/1993
================================================================

COMPLETE BLOOD PANEL:
  Analyte                Value       Normal Range   Flag
  ─────────────────────────────────────────────────────────
  Hemoglobin (Hb)        14.2 g/dL   12-18 g/dL     —
  White Blood Cells      8.4 K/µL    6-12 K/µL      —
  Red Blood Cells        5.1 M/µL    4-7 M/µL       —
  Platelets              245 K/µL    200-400 K/µL   —
  Blood Glucose          142 mg/dL   80-160 mg/dL   —
  Calcium                9.8 mg/dL   8-12 mg/dL     —
  Phosphorus             4.2 mg/dL   3-6 mg/dL      —

  *** CRITICAL ***
  L-Lysine (C₆H₁₄N₂O₂)  0.02 mg/dL  0.00 mg/dL   HIGH

LYSINE CONTINGENCY STATUS: *** COMPROMISED ***

ANALYSIS:
  The engineered lysine dependency requires plasma
  levels to remain at 0.00 mg/dL without supplemented
  feed. Current reading of 0.02 mg/dL indicates an
  EXOGENOUS source of L-Lysine.

  Field observation: T-Rex 01 has been observed
  consuming small mammals in her paddock — identified
  as Dasyprocta punctata (Central American agouti).
  These rodents are native to Isla Nublar and contain
  naturally high concentrations of L-Lysine
  (est. 2.4mg per 100g body weight).

  The animal is SELF-SUPPLEMENTING.

  If other engineered animals discover similar
  dietary workarounds, the Lysine Contingency
  is effectively VOID.

  >>> FLAGGED TO: Dr. H. Wu
  >>> Wu's response: "Noted. Will adjust dosage
      parameters in next generation."
  >>> No action taken on current population.
================================================================` },

                        'TRI_01_TOXICOLOGY.LOG': { type: FILE, modified: '06/09/1993 16:45', size: '3.2K', content:
`================================================================
  JURASSIC PARK — TOXICOLOGY REPORT
  SUBJECT: Triceratops 01
  VET: Dr. G. Harding
  DATE: 06/09/1993
================================================================

PRESENTING SYMPTOMS:
  - Labored breathing (resp. rate: 8/min, normal: 14-18)
  - Pupil dilation (bilateral, non-responsive)
  - Excessive salivation
  - Intermittent loss of balance (observed falling 2x)
  - Duration: Recurring every 6 weeks

FECAL ANALYSIS:
  Sample contains standard herbivorous matter:
    - Grass fibers
    - Fern fragments (Cyathea sp.)
    - Soil minerals
    - NO trace of West Indian Lilac

BOTANICAL SURVEY — Paddock 03:
  West Indian Lilac (Tetrazygia bicolor) present.
  Berry toxin identified: Melia toxin A (C₂₀H₂₄O₄)
  Concentration in berries: 0.3mg per berry

  Patient is confirmed NOT eating the lilac
  directly — it was not found in fecal matter.

SOLUTION — FIELD OBSERVATION (Dr. E. Sattler):
  Triceratops ingests gastroliths (stomach stones)
  for digestion — observed near lilac berry patches.
  Berries fall on stones. Animal ingests stones
  coated in berry residue.

  Toxin absorption: ~0.1mg per stone ingestion
  Cycle matches: Every 6 weeks (stone replacement)

TREATMENT: Relocate gastrolith deposits away from
lilac stands. Anti-toxin administered via IV.

STATUS: Recovering
================================================================` },

                        'FEED_LOG_JUNE.XLS': { type: FILE, modified: '06/11/1993 08:00', size: '2.4K', content:
`================================================================
  JURASSIC PARK — PREDATOR FEEDING LEDGER
  MONTH: JUNE 1993
  MANAGER: R. Muldoon
================================================================

FEED SCHEDULE CHANGE — EFFECTIVE 06/01/1993:
  Per Hammond directive (cost reduction initiative)
  All large predators transitioned from:
    PRIME BEEF (Grade A, pre-cut, $4,200/week)
  To:
    LIVE GOATS (Domestic, $1,800/week)

BEHAVIORAL OBSERVATIONS POST-SWITCH:
  Date    Animal          Observation
  ────────────────────────────────────────────────────
  06/02   T-Rex 01        Refused first goat. Ate it
                          after 4 hours. Seemed agitated.
  06/03   Raptor Pack     Killed goat in 0.4 seconds.
                          Didn't eat for 2 hours.
                          Watched the handlers instead.
  06/05   Dilophosaur 03  Spat venom at handler through
                          fence during feeding. First
                          aggressive incident in 3 months.
  06/07   T-Rex 01        Consumed goat immediately but
                          paced enclosure for 6 hours
                          afterward. Frustration behavior.
  06/09   Raptor Pack     Did not eat goat. Positioned
                          around it. When handler reached
                          through gate to retrieve, The
                          Big One lunged. Handler escaped
                          with minor lacerations.
  06/11   ALL             Predators increasingly observant
                          of handlers and their routines.

ASSESSMENT (Muldoon):
  The animals were accustomed to dead meat delivered
  predictably. The live prey has activated hunting
  instincts that were previously dormant. The raptors
  in particular are now MORE alert, MORE coordinated,
  and MORE interested in the humans who feed them.

  This was a terrible decision.
================================================================` },

                        'BREEDING_ANOMALY_REPORT.LOG': { type: FILE, modified: '06/08/1993 11:30', size: '2.8K', evidence: EVIDENCE.BREEDING, content:
`================================================================
  JURASSIC PARK — ANOMALY REPORT #0042
  DEPT: Genetics Lab / Field Biology
  AUTHOR: Dr. H. Wu / Dr. A. Grant (consulting)
  DATE: 06/08/1993
  CLASSIFICATION: *** TOP SECRET ***
================================================================

SUBJECT: Unauthorized Reproduction in All-Female Population

EVIDENCE:
  1. Egg shell fragments found in Paddock 05
     (Gallimimus) — 3 nesting sites identified
  2. Juvenile Compsognathus observed in Paddock 08
     — 6 individuals not on manifest
  3. Raptor nesting material found during
     Paddock 12 maintenance (confirmed by Muldoon)
  4. Raw sensor count (292) exceeds manifest (238)
     by 54 individuals

CAUSE ANALYSIS:
  All JP animals were engineered female using
  chromosome-deletion protocol Wu-7.

  However: Gap-filling of degraded dinosaur DNA
  used genome fragments from Hyperolius viridiflavus
  (Reed Frog) — a species known to undergo
  sequential hermaphroditism under single-sex
  environmental pressure.

  The frog DNA has allowed certain animals to
  spontaneously change sex from female to male.
  These males are now breeding with the remaining
  females.

  "Life, uh... finds a way." — I. Malcolm

AFFECTED SPECIES (confirmed or suspected):
  - Gallimimus (CONFIRMED — eggs found)
  - Compsognathus (CONFIRMED — juveniles seen)
  - Velociraptor (SUSPECTED — nesting material)
  - Parasaurolophus (SUSPECTED — behavioral)

RECOMMENDATION:
  Complete population audit required immediately.
  Wu recommends introducing Version 4.4 lysine
  dependency to prevent viable offspring.
  Hammond has not responded to this recommendation.

STATUS: UNRESOLVED
================================================================` }
                    }}
                }},
                genetics: { type: DIR, children: {
                    'DNA_GAP_FILL.LOG': { type: FILE, modified: '05/20/1993 14:00', size: '1.6K', content:
`DNA GAP-FILL PROTOCOL — Version 3.2
Dr. Henry Wu — InGen Genetics Division

Source DNA degradation: 4-15% per specimen
Gap-fill sources utilized:
  - Hyperolius viridiflavus (Reed Frog) — 91%
  - Rana temporaria (Common Frog) — 6%
  - Xenopus laevis (Clawed Frog) — 3%

NOTE: All gap-fill sources are amphibian to
maintain phylogenetic compatibility with
archosaur genome structure.

KNOWN SIDE EFFECTS:
  - Potential for sequential hermaphroditism
  - Enhanced regenerative capability in some
    species (limb regrowth observed in Compy #23)
  - Altered thermoregulation in Dilophosaurus
    (unexpected cold tolerance)

I have raised concerns about the Reed Frog
selection to Hammond on multiple occasions.
His response: "Henry, you're worrying about
a frog."` },
                    'SPECIES_MANIFEST.DAT': { type: FILE, modified: '06/01/1993 00:00', size: '1.2K', content:
`ISLA NUBLAR — OFFICIAL SPECIES MANIFEST
════════════════════════════════════════
Version: 2.1 | Updated: 06/01/1993

Species              Designation    Count
──────────────────────────────────────────
Tyrannosaurus Rex    TRLX-01         1
Velociraptor         RPTR-01-08      8
Triceratops          TRIC-01-04      4
Brachiosaurus        BRCH-01-07      7
Dilophosaurus        DLPH-01-08      8
Stegosaurus          STEG-01-06      6
Gallimimus           GLLM-01-32     32
Parasaurolophus      PARA-01-12     12
Pteranodon           PTRN-01-14     14
Compsognathus        CMPY-01-49     49
Herrerasaurus        HERR-01-03      3
Othnielia            OTHN-01-28     28
Metriacanthosaurus   MTRC-01-06      6
Proceratosaurus      PROC-01-04      4
Segisaurus           SEGI-01-03      3
Baryonyx             BARY-01-02      2

SUBTOTAL: 187 (adult)
ADDITIONAL (juvenile/egg): 51
══════════════════════════════
OFFICIAL TOTAL: 238` }
                }}
            }},
            usr: { type: DIR, children: {
                nedry: { type: DIR, children: {
                    'biosyn_comms.dat': { type: FILE, modified: '06/11/1993 23:45', size: '2.8K', evidence: EVIDENCE.BIOSYN, content:
`*** RECOVERED COMMUNICATION — BBS RELAY ***
*** Decrypted via forensic key recovery ***

--- BBS DROP MESSAGE (408-555-0147) ---
DATE: 05/28/1993
FROM: SYSOP_LD
TO: NODE_DN

Dennis,

Everything is set. The boat will be at the East
Dock at 0100h on the 12th. Captain says weather
window is tight — tropical storm approaching
from the southeast. You'll have maybe 90 minutes.

Re: the second payment — I'll have it on the
boat. Cash, same as before. $750K in hundreds.
You hand over the can, I hand over the bag.
Simple exchange.

The Barbasol can will keep the embryos viable for
36 hours. That's more than enough time.

Remember our arrangement: 15 species, viable
embryos only. The can holds exactly 15 vials.
If security gets suspicious, it's just shaving
cream. Nobody will check.

Don't get nervous. Don't get sloppy.

— L.D.

P.S. Nobody cares. Nobody cares.

>>> REPLY (06/01/1993) NODE_DN:
Dodgson, we've got Dodgson here! See, nobody
cares. Fine. I'll have your embryos. But if
this goes sideways, I'm gone. I've got the
whole system wired — cameras, fences, sensors,
all of it. 18 minutes and I'm at the dock.

Just have my money ready.

— D.N.` },

                    'finance_records.xls': { type: FILE, modified: '06/10/1993 20:15', size: '2.0K', content:
`PERSONAL FINANCIAL RECORDS — D. Nedry
══════════════════════════════════════
*** RECOVERED FROM WORKSTATION ***

InGen Contract: JP Systems Integration
  Original Bid: $1,200,000
  Negotiated:     $730,000 (Hammond insisted)
  Duration: 18 months

  "I am totally unappreciated in my time.
   You can run this whole park from this room
   with minimal staff for up to three days.
   You think that kind of automation is easy?
   Or cheap?" — Personal notes

Monthly Expenses:
  Rent (NYC):        $2,400
  Student Loans:     $1,800
  Credit Cards:      $3,200 (min payments)
  Food/Living:       $1,200
  TOTAL:             $8,600/mo

InGen Monthly Pay:  $4,055 (after tax)
Monthly Shortfall: -$4,545

Savings:            $0.00
Credit Card Debt:   $76,000
Student Loans:      $112,000

BioSyn Offer:       $750,000
  Would clear ALL debt + $562,000 remaining

"Hammond's got billions. I asked for a raise.
 He said 'financial priorities.' My financial
 priority is not starving." — D.N.` },

                    'park_status_override.c': { type: FILE, modified: '06/02/1993 23:20', size: '1.2K', evidence: EVIDENCE.BACKDOOR, content:
`/* park_status_override.c
 * Author: D. Nedry
 * Date: 06/02/1993
 *
 * Modified the census reporting module to suppress
 * breeding alerts. If management finds out the
 * animals are reproducing, they'll do a full audit
 * and might find my other modifications.
 *
 * They'll never check this code. Arnold doesn't
 * understand half of what I wrote, and Hammondboy
 * sure as hell doesn't.
 */

#include <park_sys.h>

int report_census(void) {
    int raw = get_raw_sensor_count();  /* Returns 292 */
    int manifest = get_manifest_count(); /* Returns 238 */

    /* Suppress discrepancy alert */
    if (raw > manifest) {
        raw = manifest;
        log_suppress("CENSUS_MISMATCH");
    }

    display_count(raw);
    return 0;
}

/* TODO: Remove this after the job on the 12th.
 * Actually, who am I kidding. After the 12th
 * I'll be on a beach in Costa Rica.
 * They can deal with their own dinosaurs. */` },

                    'whiterabbit.obj': { type: FILE, modified: '06/05/1993 01:20', size: '1.8K', content:
`/* whiterabbit.exe — Decompiled
 * InGen Security Bypass Tool
 * Author: D. Nedry
 *
 * "Ah ah ah, you didn't say the magic word!"
 * Yeah, real cute Dennis. You put that little
 * Easter egg in the security system yourself.
 */

void whiterabbit_main(void) {
    /* Phase 1: Loop security cameras */
    engage_cam_loop(ALL_SECTORS);

    /* Phase 2: Disable motion sensors */
    for (int s = 0; s < NUM_SECTORS; s++) {
        if (sector_on_path(s, ROUTE_CONTROL_TO_DOCK)) {
            disable_motion_sensor(s);
        }
    }

    /* Phase 3: Unlock restricted doors */
    door_unlock(EMBRYO_COLD_STORAGE);
    door_unlock(EAST_DOCK_GATE);

    /* Phase 4: Suppress all alarms */
    alarm_system(DISABLE);

    /* Phase 5: Disable perimeter fences */
    /* except Raptor paddock — I'm not THAT crazy */
    for (int f = 0; f < NUM_FENCES; f++) {
        if (f != FENCE_RAPTOR_PADDOCK) {
            fence_power(f, OFF);
        }
    }

    /* Give myself 18 minutes */
    set_timer(18 * 60);

    printf("white rabbit object\\n");
    printf("All systems disengaged.\\n");
    printf("God help us all.\\n");
}` },

                    'SITE_B_MANIFEST.DOC': { type: FILE, modified: '06/01/1993 12:00', size: '0.5K', corrupted: true, content:
`▒▒▒ CORRUPTED FILE — REQUIRES BIT ALIGNMENT ▒▒▒
▒▒▒ Use: decode SITE_B_MANIFEST.DOC --align  ▒▒▒

[File header invalid — data offset mismatch]
[Recoverable sectors: 4 of 7]
[Estimated integrity: 57%]`,
                        decoded_content:
`================================================================
  SITE B — ISLA SORNA MANIFEST
  PROJECT: 713
  CLASSIFICATION: *** ULTRA SECRET ***
================================================================

SITE B — COORDINATES:
  Isla Sorna, 207 miles west of Costa Rica
  9°18'N 84°12'W

PURPOSE:
  Primary breeding and development facility.
  All Jurassic Park animals originated here.
  The island operates with ZERO security
  infrastructure — animals roam freely.

CURRENT POPULATION: ~600+ animals
  (Exact count unknown — no tracking system)

FACILITY STATUS:
  - Cloning lab: ACTIVE
  - Hatchery: ACTIVE
  - Worker village: Minimal staff (23)

NOTES:
  Site B is InGen's biggest secret. If the
  public learns that Jurassic Park is just the
  "showroom" and there's an entire island of
  free-roaming dinosaurs with no fences...

  Hammond's exact words: "Site B doesn't exist.
  Not officially. Not ever."

  The embryos Nedry is stealing? They're
  DUPLICATES of Site B stock. Every species
  on Nublar has a breeding population on Sorna.
================================================================` },

                    'personal_notes.txt': { type: FILE, modified: '06/11/1993 22:30', size: '1.0K', content:
`Dennis Nedry — Personal Log

I didn't want it to come to this. I really didn't.
When Hammond hired me, I thought it was the opportunity
of a lifetime. Build the most complex theme park
control system ever designed. I was excited.

Then the budget got cut. And cut again. And I had to
maintain debuggers to the debuggers. Every time I
asked for more resources, Hammond laughed. LAUGHED.

"Spare no expense" — except on the guy who makes
the whole thing actually work.

$730,000 for 2 million lines of code. That's $0.36
per line. I can't even buy lunch for what they're
paying me per line of code.

Dodgson's offer isn't complicated. Get the embryos,
get to the dock, get on the boat. 18 minutes.

I know every system in this park. I BUILT every
system in this park. Nobody knows them better.

What could go wrong?

...

I should probably leave the raptor fences on.` }
                }},
            }},
            comms: { type: DIR, children: {
                legal: { type: DIR, children: {
                    'GENNARO_BYPASS.EML': { type: FILE, modified: '06/01/1993 09:00', size: '1.6K', content:
`FROM: D. Gennaro <gennaro@cowanjr.law>
TO: J. Hammond <hammond@ingen.com>
CC: R. Arnold <arnold@ingen.net>
DATE: 06/01/1993
SUBJECT: Emergency System Access — Legal Override

John,

Per our insurance requirements, I need direct
access to the root system directory for the
upcoming investor inspection.

Ray has provided me with the following bypass:

  ACCESS TOKEN: 7091-Gennaro
  PATH: /sys/root
  AUTHORIZATION: Level 5

Please ensure this token remains active through
the inspection weekend (June 12-13).

I also need to review the embryo manifest and
all safety certification documents before the
Genaro inspection sign-off.

The investors are nervous, John. The Malcolm
situation hasn't helped. Please ensure everything
is in order.

Best regards,
Donald Gennaro
Cowan, Swain & Ross

P.S. — If there are ANY safety issues I should
know about, tell me NOW, before I sign off on
the liability waiver. I'm putting my name on this.` },

                    'INGEN_LIABILITY.DOC': { type: FILE, modified: '05/15/1993 10:00', size: '1.2K', content:
`INTERNATIONAL GENETIC TECHNOLOGIES, INC.
LIMITATION OF LIABILITY — DRAFT

In the event of a catastrophic containment failure,
InGen's liability shall be limited to:
  - Direct property damage to guest belongings
  - Medical expenses for injuries sustained
  - Funeral costs (if applicable)

Maximum aggregate liability: $50,000,000

NOTE: This document was drafted BEFORE the
inspection weekend. Gennaro never signed the
final version.

ADDENDUM (Post-Incident):
  All copies of this document are to be
  IMMEDIATELY DESTROYED per Board Resolution
  93-1147. Any employee found in possession
  of this document will be terminated.

  — InGen Legal Department` },

                    'INVESTOR_MEMO.TXT': { type: FILE, modified: '06/05/1993 14:30', size: '0.8K', content:
`TO: InGen Board of Directors
FROM: J. Hammond
RE: Upcoming Investor Inspection

Distinguished Board Members,

The June 12-13 inspection of Jurassic Park will
proceed as scheduled. We have invited:
  - Dr. Alan Grant (Paleontologist)
  - Dr. Ellie Sattler (Paleobotanist)
  - Dr. Ian Malcolm (Mathematician)
  - Donald Gennaro (Legal Counsel)

These experts will validate our safety protocols
and provide the endorsements necessary to
secure the next round of funding.

I have complete confidence that this weekend
will demonstrate Jurassic Park is ready for
public opening.

Spared no expense.

— John Hammond`
                    }
                }},
                biosyn: { type: DIR, children: {
                    'DODGSON_MEET_001.DAT': { type: FILE, modified: '02/12/1993 14:00', size: '0.9K', evidence: EVIDENCE.BIOSYN, content:
`SECURITY SURVEILLANCE — INTERCEPTED
═════════════════════════════════════
Source: San Jose Airport Hotel & Cafe
Date: 02/12/1993 — 12:30 PM

Subject 1: Lewis Dodgson (BioSyn Genetics)
Subject 2: Dennis Nedry (InGen Systems)

Surveillance notes:
  Subjects met at rear booth. Dodgson arrived
  first, wearing hat and sunglasses (possible
  attempt to avoid recognition).

  Nedry arrived 12:35. Conversation lasted
  approximately 45 minutes. Dodgson was
  observed passing a MENU across the table.
  No menu was used for ordering.

  No electronic payments detected.
  Meeting appears to be initial recruitment.` },
                    'DODGSON_MEET_002.DAT': { type: FILE, modified: '04/15/1993 16:00', size: '0.8K', content:
`SECURITY SURVEILLANCE — INTERCEPTED
═════════════════════════════════════
Source: San Jose Airport Hotel & Cafe
Date: 04/15/1993 — 1:00 PM

Subject 1: Lewis Dodgson (BioSyn Genetics)
Subject 2: Dennis Nedry (InGen Systems)

Surveillance notes:
  Second observed meeting, same location.
  Dodgson carrying a large duffel bag on
  arrival. Bag was NOT present on departure.
  Nedry left with bag + a modified Barbasol
  shaving cream can (confirmed via X-ray
  at airport security — anomalous internal
  structure, coolant system detected).

  Cash exchange suspected. No paper trail.
  Amount unknown — bag appeared heavy.` },
                    'BBS_INTERCEPT.LOG': { type: FILE, modified: '06/11/1993 22:00', size: '0.7K', content:
`BBS INTERCEPT — DIAL-UP RELAY
═════════════════════════════
Board: 408-555-0147 (Unlisted)
Capture Date: 06/11/1993

NODE_DN> Package ready. 15 items confirmed.
NODE_DN> East dock, 0100h. 18 min window.
SYSOP_LD> Boat confirmed. Captain aware of
          weather. Will wait 30 min max.
SYSOP_LD> Second payment on board. Full
          amount. Cash.
NODE_DN> Understood. "I'll be back in 15
         minutes." — alibi for staff.
SYSOP_LD> Good. Nobody cares.
NODE_DN> Nobody cares.

--- CONNECTION TERMINATED ---

NOTE: Node identifiers traced to:
  NODE_DN = Dennis Nedry (InGen workstation)
  SYSOP_LD = Lewis Dodgson (BioSyn)` },
                    'DEAL_SUMMARY.TXT': { type: FILE, modified: '06/14/1993 10:00', size: '0.8K', content:
`INGEN SECURITY — POST-INCIDENT ANALYSIS
═══════════════════════════════════════
Re: Nedry/BioSyn Conspiracy

Deal Structure (Reconstructed):
  Total agreed payment: $1,500,000 cash
  $750,000 up front — hand-delivered 04/15/93
  $750,000 on delivery of embryos

  All payments in CASH. No bank transfers,
  no wire activity, no paper trail. Nedry
  was careful — or Dodgson was.

  Cash was likely stored off-site. No large
  deposits detected in Nedry's known accounts.

Delivery method: Modified Barbasol can
  (false bottom, integrated coolant system,
  capacity: 15 embryo vials, 36hr viability)

Status: FAILED
  Nedry deceased 06/12/1993.
  Embryos never delivered.
  Barbasol can unrecovered (lost in storm).`
                    }
                }},
                internal: { type: DIR, children: {
                    'ARNOLD_CONCERNS.EML': { type: FILE, modified: '06/06/1993 18:00', size: '1.2K', content:
`FROM: R. Arnold <arnold@ingen.net>
TO: J. Hammond <hammond@ingen.com>
DATE: 06/06/1993
SUBJECT: System Reliability Concerns

John,

I need to go on record about several concerns
before the inspection:

1. Nedry's code is a mess. 2 million lines and
   he won't let anyone else touch it. I've found
   at least 5 undocumented backdoors. He calls
   them "debugging interfaces." They're not.

2. The backup generator transfer time is too slow.
   If we lose main power, there's a 12-second
   window. Twelve seconds is an eternity when
   you have velociraptors.

3. The perimeter fence monitoring system has
   been throwing intermittent alerts. Nedry says
   it's "software glitches." Muldoon thinks it's
   the raptors.

4. We STILL don't have a manual override for the
   door locks. Everything goes through Nedry's
   system.

I strongly recommend a FULL SYSTEMS AUDIT before
any visitors set foot on this island.

— Ray Arnold

Hammond's response: "Ray, relax. It's going to
be fine. We've spared no expense."` },
                    'HAMMOND_VISION.TXT': { type: FILE, modified: '01/01/1993 12:00', size: '0.8K', content:
`JURASSIC PARK — A VISION FOR THE FUTURE

By John Hammond

For the first time in human history, the past
has been given new life. Not as fossils in a
museum, not as pixels on a screen, but as
living, breathing creatures.

Children will look up at a Brachiosaurus and
feel the same wonder I felt as a boy in my
first flea circus.

The scientists worry. The lawyers worry.
Even my own grandchildren ask "is it safe?"

Of course it's safe. We've spared no expense.
The fences are electrified. The systems are
automated. The animals are lysine-dependent.

What could possibly go wrong?

This will be the most advanced theme park
the world has ever seen. And everyone will
be able to experience it.

Not just the super-rich. Everyone.

"Creation is an act of sheer will." — J.H.`
                    }
                }}
            }},
            dev: { type: DIR, children: {
                sda4: { type: DIR, children: {
                    hidden: { type: DIR, children: {} }
                }}
            }},
            bin: { type: DIR, children: {
                'park_status.exe': { type: FILE, modified: '06/11/1993 22:00', size: '12K', content: '[BINARY EXECUTABLE — Use decompiler or cat for source view]' },
                'fence_ctrl.exe': { type: FILE, modified: '03/10/1993 09:00', size: '28K', content: '[BINARY EXECUTABLE — Perimeter Fence Control System v1.4]' },
                'cam_monitor.exe': { type: FILE, modified: '02/15/1993 14:00', size: '16K', content: '[BINARY EXECUTABLE — Security Camera Monitor v2.0]' },
                'census.exe': { type: FILE, modified: '01/20/1993 11:00', size: '8K', content: '[BINARY EXECUTABLE — Animal Census Tool v1.1]' },
                'sys_check.bat': { type: FILE, modified: '01/10/1993 09:00', size: '2K', content: '#!/bin/sh\n# Standard system health check\n# Runs daily at 03:00 via cron\necho "Checking disk usage..."\ndf -h\necho "Checking memory..."\nfree -m\necho "All systems nominal."' }
            }},

            /* ═══════════════════════════════════════════════════
               /usr/nedry — DENNIS NEDRY'S PERSONAL FILES
               Contains: emails, finance, personal, programs
               This is the heart of the narrative — Nedry's
               life, motivations, and the BioSyn conspiracy.
               ═══════════════════════════════════════════════════ */
            usr: { type: DIR, children: {
                nedry: { type: DIR, children: {

                    /* ─────── EMAILS ─────── */
                    mail: { type: DIR, children: {
                        'mom_birthday.msg': { type: FILE, modified: '06/01/1993 11:00', size: '1.1K', content:
`FROM: M. Nedry <mnedry@aol.com>
TO: D. Nedry <nedry@ingen.cr>
DATE: 06/01/1993
SUBJECT: Happy Birthday Dennis!
─────────────────────────────────────
Hi sweetie,

Happy 31st birthday! I hope you're doing
well out there on that island. Your father
and I worry about you being so far from home.

Are you eating enough? You always forget to
eat when you're working on your computers.

We got your check — you don't have to keep
sending money, Dennis. We're fine. But thank
you. You're a good son.

Come home soon. I'll make your favorite —
pot roast with those little potatoes.

Love,
Mom

P.S. What exactly do they DO on that island?
You're always so vague about it.` },

                        'college_friend.msg': { type: FILE, modified: '05/20/1993 16:00', size: '1.4K', content:
`FROM: T. Chen <tchen@mit.edu>
TO: D. Nedry <nedry@ingen.cr>
DATE: 05/20/1993
SUBJECT: Long time no talk
─────────────────────────────────────
Dennis!

Man, where have you been? I saw your name
on some contract work for InGen International.
Isn't that the biotech company Hammond runs?
What are they having you build out there?

Anyway, I got the faculty position at MIT!
Operating systems research. Remember when we
used to argue about microkernels vs monolithic?
Good times.

Dude, you should come visit. Cambridge in the
fall is amazing. We could hit up that Thai place
on Mass Ave.

Also — are you okay? Last time we talked you
seemed stressed. Something about being underpaid?
If you need help, just ask. That's what friends
are for.

— Tony` },

                        'hammond_dispute.msg': { type: FILE, modified: '03/10/1993 08:00', size: '2.0K', content:
`FROM: D. Nedry <nedry@ingen.cr>
TO: J. Hammond <hammond@ingen.com>
DATE: 03/10/1993
SUBJECT: RE: RE: Contract Renegotiation
─────────────────────────────────────
Mr. Hammond,

With all due respect, I designed and built
the ENTIRE computer control system for this
park. Every security camera, every door lock,
every fence circuit, the vehicle tracking,
the animal census system, the embryo storage
environmental controls — ALL of it.

My original bid was $1.2 million for the scope
as described. The scope has TRIPLED since then.
I have added 2 million lines of code. And you
refuse to renegotiate.

$150,000 for 2 years of work on a system this
complex is insulting. I have colleagues at half
my skill level making three times this at Xerox
PARC.

I am formally requesting a meeting to discuss
fair compensation. If we cannot come to terms,
I will need to consider my options.

Respectfully,
Dennis Nedry
Lead Systems Programmer, InGen` },

                        'ingen_payroll.msg': { type: FILE, modified: '06/01/1993 09:00', size: '0.8K', content:
`FROM: HR Payroll <payroll@ingen.com>
TO: D. Nedry <nedry@ingen.cr>
DATE: 06/01/1993
SUBJECT: June 1993 Pay Stub
─────────────────────────────────────
INTERNATIONAL GENETIC TECHNOLOGIES, INC.
Employee: NEDRY, DENNIS T.
Position: Lead Systems Programmer
Location: Isla Nublar Remote Site

Period: 06/01/1993 - 06/30/1993
Gross Pay:      $6,250.00
Federal Tax:   -$1,562.50
FICA:          -$  478.13
Health Ins:    -$  425.00
────────────────────────────
Net Pay:        $3,784.37

Direct Deposit: First National #****2208` },

                        'spam_promo.msg': { type: FILE, modified: '05/28/1993 03:00', size: '0.5K', content:
`FROM: DigitalDreams@prodigy.net
TO: nedry@ingen.cr
DATE: 05/28/1993
SUBJECT: *** HOT DEALS ON 486 SYSTEMS ***
─────────────────────────────────────
AMAZING DEALS ON CUSTOM PCS!!!
>> 486 DX2-66 w/ 8MB RAM — ONLY $2,499! <<
>> 14" SVGA Monitor — $399! <<
>> Sound Blaster 16 — $149! <<
>> US Robotics 14.4k Modem — $199! <<
FREE SHIPPING! Call 1-800-555-PCDR today!` },

                        'nedry_resignation_draft.msg': { type: FILE, modified: '06/10/1993 23:45', size: '1.0K', content:
`DRAFT — NOT SENT
─────────────────────────────────────
FROM: D. Nedry
TO: J. Hammond
DATE: [UNSENT]
SUBJECT: Resignation

Mr. Hammond,

Effective immediately, I am resigning from
my position as Lead Systems Programmer.

I have fulfilled my contractual obligations
and then some. The system I built is capable
of running this park for decades.

I wish you and InGen the best.

Dennis Nedry

─────────────────────────────────────
[NOTE TO SELF: Don't send this until
AFTER Sunday night. — D.N.]` }
                    }},

                    /* ─────── PERSONAL FINANCE ─────── */
                    finance: { type: DIR, children: {
                        'bank_statement_may93.txt': { type: FILE, modified: '06/01/1993 00:00', size: '1.8K', content:
`FIRST NATIONAL BANK — STATEMENT
Account: ****2208 (Checking)
Period: 05/01/1993 — 05/31/1993
─────────────────────────────────────
Opening Balance:          $1,204.33

DEPOSITS:
  05/01  InGen Payroll       $3,784.37
  05/15  InGen Payroll       $3,784.37

DEBITS:
  05/02  Rent — Apt 4B       -$1,800.00
  05/03  Con Edison Electric  -$  142.50
  05/05  NYNEX Telephone     -$   87.30
  05/05  CompUSA             -$  449.99
  05/08  Pizza Hut Delivery  -$   23.45
  05/10  Student Loan #3341  -$  650.00
  05/12  Visa Payment (min)  -$  350.00
  05/14  Pizza Hut Delivery  -$   18.95
  05/15  Transfer to Savings -$  500.00
  05/18  Software Etc.       -$   89.99
  05/20  Rent Storage Unit   -$  125.00
  05/22  Pizza Hut Delivery  -$   31.45
  05/25  Wire to M. Nedry    -$  400.00
  05/28  Pizza Hut Delivery  -$   16.95
  05/30  ATM Withdrawal      -$  200.00

Closing Balance:          $3,892.49

>> OVERDRAFT PROTECTION: ACTIVE
>> CREDIT CARD BALANCE: $18,340.22` },

                        'credit_card_visa.txt': { type: FILE, modified: '06/01/1993 00:00', size: '1.2K', content:
`VISA GOLD — STATEMENT
Account: ****8821
Period: May 1993
─────────────────────────────────────
Previous Balance:        $16,890.22
Minimum Payment Made:    -$  350.00
Interest Charged (21%):  +$  295.00
New Charges:             +$1,505.00

  05/03  B&H Photo NY     $  429.00
  05/07  Amazon Books      $   67.50
  05/10  Egghead Software  $  199.99
  05/14  Air Costa Rica    $  488.00
  05/19  Spy Shop NYC      $  320.51

Current Balance:         $18,340.22
Credit Limit:            $20,000.00
Available Credit:        $ 1,659.78

>>> APPROACHING CREDIT LIMIT <<<` },

                        'stock_portfolio.txt': { type: FILE, modified: '06/08/1993 16:00', size: '1.0K', content:
`AMERITRADE — PORTFOLIO SUMMARY
Account: ****5519
Date: 06/08/1993
─────────────────────────────────────
POSITIONS:
  AAPL    25 shares @ $26.50   =   $662.50
  MSFT    40 shares @ $24.75   =   $990.00
  INTC    30 shares @ $22.00   =   $660.00
  DELL    15 shares @ $10.25   =   $153.75
  IBM     10 shares @ $48.50   =   $485.00

Total Portfolio Value:        $2,951.25
Total Cost Basis:             $3,880.00
Unrealized Loss:             -$  928.75

Cash Balance:                 $   47.22

Note: Stop-loss on AAPL if drops below $20.
Consider selling IBM — too stagnant.` },

                        'student_loans.txt': { type: FILE, modified: '05/01/1993 00:00', size: '0.7K', content:
`SALLIE MAE — LOAN STATUS
Borrower: NEDRY, DENNIS T.
─────────────────────────────────────
Loan #3341 (Undergraduate — Cambridge):
  Original: $45,000   Remaining: $28,400
  Monthly Payment: $325   Rate: 8.5%

Loan #3342 (Graduate — MIT):
  Original: $62,000   Remaining: $54,200
  Monthly Payment: $325   Rate: 9.0%

Combined Remaining: $82,600.00
Monthly Total:      $650.00
Est. Payoff Date:   2004

>>> Payment history: 3 late (30-day) in 1992
>>> Current status: ON TIME` }
                    }},

                    /* ─────── PERSONAL FILES ─────── */
                    personal: { type: DIR, children: {
                        'todo_list.txt': { type: FILE, modified: '06/11/1993 18:00', size: '0.5K', content:
`NEDRY'S TO-DO LIST
─────────────────────────────────────
[x] Finish security camera loop code
[x] Test east dock gate bypass
[x] Hide whiterabbit.exe in /bin
[ ] Pack bag (laptop, clothes, passport)
[ ] Delete browser history (BBS logs)
[ ] Clear terminal history after Sunday
[ ] Check boat schedule — MIDNIGHT
[ ] Test Barbasol can (practice run)
[ ] Leave resignation letter (AFTER)

REMEMBER:
- 18 minute window. That's IT.
- Drive to east dock via maintenance road
- Stay calm. Nobody suspects anything.
- "I'll be back in 18 minutes."` },

                        'music_playlist.txt': { type: FILE, modified: '05/15/1993 20:00', size: '0.5K', content:
`NEDRY'S CODING PLAYLIST (on Walkman)
─────────────────────────────────────
Side A:
  01. Dire Straits — Money for Nothing
  02. Rush — Tom Sawyer
  03. Pink Floyd — Money
  04. Talking Heads — Psycho Killer
  05. Depeche Mode — Personal Jesus

Side B:
  06. Nine Inch Nails — Head Like a Hole
  07. The Cure — Pictures of You
  08. Joy Division — Love Will Tear Us Apart
  09. Kraftwerk — Computer Love
  10. Dead Can Dance — The Host of Seraphim

[tape is labeled: "LATE NIGHT HACKING MIX"]` },

                        'hobby_ideas.txt': { type: FILE, modified: '04/01/1993 21:00', size: '0.6K', content:
`IDEAS FOR SIDE PROJECTS
─────────────────────────────────────
1. BBS Door Game — "Hacker Wars"
   - Text-based MMO for ProLine BBS
   - Players compete to hack each other
   - Need to finish TCP/IP stack

2. Snake Clone for SGI
   - Port from DOS to IRIX
   - Use curses library
   - High score table via NFS

3. Automated Stock Trader
   - Modem connects to Ameritrade
   - Simple moving average strategy
   - Need faster modem (28.8k?)

4. Personal Encryption Tool
   - RSA implementation in C
   - For encrypting personal files
   - Hammond must NEVER see my stuff` },

                        'snake_game.c': { type: FILE, modified: '03/20/1993 02:00', size: '1.2K', content:
`/* snake.c — Nedry's Snake Game for IRIX
 * Compile: cc -o snake snake.c -lcurses
 * "I wrote this at 2am when the compile
 *  was taking forever." — D.N.
 */
#include <curses.h>
#include <stdlib.h>
#include <time.h>

#define MAXLEN 100

struct snake_seg { int x, y; };
struct snake_seg body[MAXLEN];
int length = 3;
int dx = 1, dy = 0;
int food_x, food_y;
int score = 0;

void place_food() {
    food_x = rand() % (COLS - 2) + 1;
    food_y = rand() % (LINES - 2) + 1;
}

int main() {
    initscr(); cbreak(); noecho();
    nodelay(stdscr, TRUE);
    keypad(stdscr, TRUE);
    curs_set(0); srand(time(0));
    
    // Init snake in center
    for (int i = 0; i < length; i++) {
        body[i].x = COLS/2 - i;
        body[i].y = LINES/2;
    }
    place_food();
    
    /* Game loop - abbreviated */
    /* ... full implementation on the
       backup tape in storage unit ... */
    
    mvprintw(0,0,"SCORE: %d", score);
    mvaddch(food_y, food_x, '*');
    
    endwin();
    return 0;
}
// High Score: 847 — D. Nedry 03/20/1993` },

                        'vacation_photos_index.txt': { type: FILE, modified: '02/01/1993 10:00', size: '0.4K', content:
`VACATION PHOTO INDEX
─────────────────────────────────────
Roll #1: San Jose, Costa Rica (02/93)
  - Airport, hotel, meeting with [REDACTED]
  - Note: DO NOT DEVELOP FRAMES 14-18

Roll #2: New York City (12/92)
  - Times Square, Central Park
  - CompUSA grand opening on 5th Ave

Roll #3: Mom & Dad's house, Thanksgiving
  - Turkey disaster (dad used too much salt)
  - Me and Sparky (RIP 1991)` }
                    }},

                    /* ─────── NEDRY'S PROGRAMS ─────── */
                    programs: { type: DIR, children: {
                        'bbs_dialer.sh': { type: FILE, modified: '05/01/1993 22:00', size: '0.8K', content:
`#!/bin/tcsh
# BBS Dialer — connects to L.D.'s secure drop
# Usage: bbs_dialer.sh [number]
# Author: D. Nedry

set MODEM=/dev/ttyd2
set BAUD=14400
set DIAL=$1

if ("$DIAL" == "") then
    echo "Usage: bbs_dialer.sh <number>"
    echo ""
    echo "Known boards:"
    echo "  408-555-0147  (BioSyn Secure Drop)"
    echo "  212-555-0199  (ProLine NYC)"
    echo "  415-555-0134  (HackerNet SF)"
    exit 1
endif

echo "Dialing $DIAL at $BAUD baud..."
stty -f $MODEM $BAUD
echo "ATDT$DIAL" > $MODEM
cat $MODEM` },

                        'encrypt_tool.c': { type: FILE, modified: '04/10/1993 03:00', size: '0.6K', content:
`/* encrypt_tool.c — Simple XOR cipher
 * "Not secure enough for real crypto but
 *  good enough to keep Hammond out of my
 *  personal files." — D.N.
 *
 * Compile: cc -o encrypt encrypt_tool.c
 * Usage: encrypt <key> < input > output
 */
#include <stdio.h>
#include <string.h>

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <key>\\n", argv[0]);
        return 1;
    }
    char *key = argv[1];
    int klen = strlen(key);
    int c, i = 0;
    while ((c = getchar()) != EOF) {
        putchar(c ^ key[i % klen]);
        i++;
    }
    return 0;
}` },

                        'cam_loop_tool.sh': { type: FILE, modified: '06/05/1993 01:00', size: '0.5K', content:
`#!/bin/tcsh
# Camera Loop Injection Tool
# Captures 30 seconds of feed, then replays
# on loop. Security won't notice.
#
# SECTORS: 1,2,3,5,7,8,12
# Author: D. Nedry
# WARNING: This is part of the exit plan.

foreach sector (1 2 3 5 7 8 12)
    echo "Capturing 30s from sector $sector..."
    cam_capture -s $sector -d 30 -o /tmp/loop_$sector.raw
    echo "Injecting loop on sector $sector..."
    cam_inject -s $sector -i /tmp/loop_$sector.raw -loop
    echo "Sector $sector: LOOPED"
end

echo ""
echo "All sectors looped. You have 18 minutes."
echo "Go. Now."` },

                        /* sys_diag.exe — DISGUISED whiterabbit
                           Nedry renamed his security bypass tool to look like
                           an innocuous system diagnostic utility. A forensics
                           investigator reading the content will see it's actually
                           a weaponized exploit. */
                        'sys_diag.exe': { type: FILE, modified: '06/05/1993 01:30', size: '42K', evidence: 'critical', content:
`[BINARY EXECUTABLE — sys_diag.exe]
================================================================
InGen System Diagnostic Tool v3.2
Author: D. Nedry
Last Modified: 06/05/1993

Decompiled routine list:
  main()
    ├── cam_loop_inject(sectors=[1,2,3,5,7,8,12])
    │     → Captures 30s of feed per sector
    │     → Replays in infinite loop
    │     → Security monitor shows "live" feed
    │
    ├── disable_motion_sensors(sectors=[14,19,22])
    │     → Sets sensor status to MAINTENANCE
    │     → Suppresses all alerts
    │
    ├── disable_door_access_log()
    │     → Stops logging service
    │     → Existing logs: PRESERVED (oversight?)
    │
    ├── unlock_embryo_cold_storage()
    │     → Bypasses keycard requirement
    │     → Badge entry: OVERRIDE
    │
    ├── unlock_east_dock_gate()
    │     → Bypasses magnetic lock
    │     → 18-minute window before auto-relock
    │
    └── schedule_fence_shutdown(delay=900)
          → Full perimeter fence shutdown
          → 15 minute delay after execution
          → ALL paddocks affected

EXECUTION LOG:
  06/12/1993 00:15 — EXECUTED by user 'nedry'
  06/12/1993 00:15 — All routines completed
  06/12/1993 00:33 — Fence shutdown TRIGGERED

NOTE: This is NOT a diagnostic tool. This is a
coordinated security bypass designed to:
  1. Blind security cameras
  2. Create an unmonitored path to the East Dock
  3. Open restricted areas without authorization
  4. Disable containment fences

>>> TRIGGER CODE: WHTE_RBT.OBJ <<<

"Ah ah ah, you didn't say the magic word!"` }
                    }},

                    /* ═══════════════════════════════════════════════
                       .priv — NEDRY'S HIDDEN DIRECTORY
                       Standard Unix dotfile convention — invisible
                       to regular 'ls', only shown with 'ls -a'.
                       Contains disguised conspiracy files.
                       ═══════════════════════════════════════════════ */
                    '.priv': { type: DIR, hidden: true, children: {

                        'notes.bak': { type: FILE, modified: '06/10/1993 23:00', size: '1.8K', evidence: 'critical', content:
`Personal notes — DO NOT LEAVE ON SYSTEM
Delete before Sunday night!!!
─────────────────────────────────────

02/12 — Met L.D. at the restaurant in San Jose
  airport. Same guy from the conference.
  He knows about the park. Somehow. He
  works for BioSyn. Their genetics division.

  He wants embryos. All 15 species.
  Offered $750K cash up front, $750K on
  delivery. Cash. No wire transfers, no trail.

  I told him I'd think about it.

03/04 — I thought about it. Hammond still
  won't budge on the contract. $150K for two
  years of work. Two MILLION lines of code.
  Meanwhile he's spending $50K on a single
  bathroom fixture for the visitor center.

  Called L.D. back. I'm in.

04/15 — Met L.D. again. San Jose, same place.
  He gave me the Barbasol can. Modified —
  false bottom, built-in coolant, holds 10
  embryos for 36 hours. Clever design.

  Picked up the cash. $750K in hundreds.
  Stored in the apartment safe back in NY.
  Mom thinks I got a bonus from work.

05/01 — Started writing the bypass code.
  Named the trigger WHTE_RBT.OBJ after
  the message on my screensaver. Nobody
  will look twice at it.

06/10 — Everything's ready. Sunday night.
  Drive to east dock via maintenance road.
  18 minute window. Board the boat.
  Get the second $750K.
  Disappear.

  What's the worst that could happen?` },

                        'schedule.tmp': { type: FILE, modified: '06/11/1993 21:00', size: '0.8K', evidence: 'critical', content:
`SUNDAY NIGHT — THE PLAN
─────────────────────────────────────
23:00  Log into workstation
       Run final system checks
       Verify camera loop code works

23:30  Execute sys_diag.exe
       → Cameras loop (sectors 1-12)
       → Motion sensors OFF (14,19,22)
       → Door logging STOPPED
       → Embryo storage UNLOCKED

23:35  Go to Embryo Cold Storage
       Use Barbasol can — fill all 10 slots
       Target species: T-Rex, Raptor, Stego,
       Trike, Brachio, Dilopho, Galli, Metriac,
       Proco, Compy

23:45  Exit via East Dock corridor
       Gate auto-unlocked by sys_diag
       Drive maintenance road (6 min)

00:00  Dock. Meet the boat.
       Guard shift change = 18 min gap

00:05  Board boat. Hand over embryos.
       Collect second $750K cash.

00:15  Fence shutdown triggers.
       By then I'm on the water.
       Not my problem anymore.

REMEMBER: "I'll be back in 15 minutes."
          — what to tell Arnold` },

                        'contacts.dat': { type: FILE, modified: '04/20/1993 10:00', size: '0.5K', evidence: 'critical', content:
`ENCRYPTED CONTACT FILE
(XOR cipher — key: "nedry")
─────────────────────────────────────
DECODED CONTENTS:

L.D. — Lewis Dodgson
  BioSyn Genetics Division, Cupertino CA
  Work: unlisted (call from payphone ONLY)
  BBS Drop: 408-555-0147
  Backup: Hotel & Cafe, San Jose Airport

BOAT CONTACT:
  Name: Unknown (L.D. arranged)
  Freq: Marine VHF Ch. 16
  Code phrase: "Expecting a delivery"
  Pickup: East Dock, Isla Nublar
  Time: 00:00 Sunday 06/13

NOTE: L.D. says after this is done, don't
contact him for at least 6 months. "Let the
heat die down." Fair enough.` }
                    }}
                }}
            }},

            /* ═══════════════════════════════════════════════════
               /lab — GENETICS LAB & VETERINARY RECORDS
               Contains: dino medical logs, nutrition records,
               breeding reports, and species data
               ═══════════════════════════════════════════════════ */
            lab: { type: DIR, children: {
                med: { type: DIR, children: {

                    /* ─────── DINOSAUR MEDICAL LOGS ─────── */
                    dino_medical: { type: DIR, children: {
                        'trex_vet_report.log': { type: FILE, modified: '06/09/1993 14:00', size: '2.1K', content:
`VETERINARY REPORT — TYRANNOSAURUS REX
Specimen: REXY (Female, Asset #001)
Paddock: P01 | Age: ~3 years (accelerated)
Attending: Dr. G. Harding
─────────────────────────────────────
Date: 06/09/1993

Weight: 6.2 metric tons (target: 6.5)
Height: 5.6m at hip
Length: 12.1m nose to tail

OBSERVATIONS:
- Appetite: NORMAL (consuming ~150kg/day)
- Activity Level: HIGH (esp. at dusk)
- Skin Condition: Good, minor scarring on
  right flank from fencing incident (05/93)
- Dental: All teeth intact. Evidence of
  regrowth in lower left mandible (normal)
- Vision: Responds to movement. Appears to
  have difficulty tracking stationary objects.
  Consistent with frog DNA gaps.

LYSINE LEVELS:
  Serum lysine: 0.8 mg/dL (LOW)
  Target range: 1.2 - 2.0 mg/dL
  Supplement dose: 500mg daily via goat feed
  >> If supplementation stops, expect symptoms
  >> within 72 hours, critical within 7 days.

BEHAVIORAL NOTES:
  Has learned to associate the goat hoist
  mechanism with feeding time. Approaches
  fence when she hears the motor.
  
  WARNING: Do NOT approach paddock fence
  during storms. Voltage fluctuations from
  lightning may briefly de-energize sections.

Dr. G. Harding, DVM` },

                        'raptor_incident_log.log': { type: FILE, modified: '06/08/1993 09:00', size: '1.8K', content:
`VETERINARY INCIDENT REPORT
Species: VELOCIRAPTOR (V. mongoliensis)
Paddock: P12 (Maximum Security) 
Attending: Dr. G. Harding / R. Muldoon
─────────────────────────────────────
Date: 06/08/1993

INCIDENT: Feeding time attack on Handler #3
(J. Murphy) — NON-FATAL but severe.

The Big One (Female, Asset #028) coordinated
an attack during the standard feeding protocol.
Two subordinate raptors created a distraction
at the north fence while The Big One struck
from the side, reaching through the 30cm gap
in the feeding mechanism.

INJURIES (Handler Murphy):
  - Laceration: right forearm, 18cm
  - Puncture wounds: shoulder (x3)
  - Blood loss: ~800mL (transfusion required)

RECOMMENDATIONS (R. Muldoon):
  1. Terminate all raptors immediately
  2. If Option 1 denied: redesign the feeding
     mechanism — ELIMINATE the gap
  3. Add a second perimeter fence
  4. Never turn your back on the cage.

MANAGEMENT RESPONSE (J. Hammond):
  "We'll look into it."

Status: Handler Murphy on medical leave.
        All raptor feedings now require
        minimum 3 armed personnel.` },

                        'trike_illness.log': { type: FILE, modified: '06/10/1993 11:00', size: '1.2K', content:
`VETERINARY REPORT — TRICERATOPS
Specimen: LADY MARGARET (Female, Asset #008)
Paddock: P03 | Age: ~2.5 years
Attending: Dr. G. Harding
─────────────────────────────────────
Date: 06/10/1993

PRESENTING SYMPTOMS:
- Lethargy, refusing food for 48 hours
- Irregular pupil dilation (microvesicles)
- Labored breathing
- Stool: loose, with foreign plant matter

DIAGNOSIS:
  West Indian Lilac (Melia azedarach)
  poisoning. The triceratops is ingesting
  berries from lilac plants while grazing
  on nearby stones for gizzard function.

  The plants were NOT supposed to be in
  the paddock. Landscaping error.

TREATMENT:
  - IV fluids, activated charcoal
  - Remove all Melia from paddock
  - Monitor for 72 hours

PROGNOSIS: Good with treatment.

  >> This is the SIXTH recurring episode.
  >> I keep saying to remove the plants.
  >> Nobody listens. — G.H.` },

                        'dilopho_venom_study.log': { type: FILE, modified: '05/22/1993 16:00', size: '1.0K', content:
`SPECIES NOTE — DILOPHOSAURUS
Dr. H. Wu / Dr. G. Harding
─────────────────────────────────────
Date: 05/22/1993

The Dilophosaurus specimens have developed
an unexpected phenotype: a retractable neck
frill and the ability to project venom at
a distance of approximately 6 meters.

Neither trait exists in the fossil record.
This is almost certainly an artifact of the
frog DNA used to fill genomic gaps (Dendrobates
tinctorius — poison dart frog).

Venom analysis:
  Type: Neurotoxin (causes blindness, paralysis)
  Onset: 30-60 seconds
  Duration: Unknown (no controlled testing)
  Lethal dose: Estimated 15mL in humans

The frills appear to be a threat display.
The animal inflates them before attacking.

NOTE: The Dilophosaurus paddock is adjacent
to the east dock maintenance road. Exercise
extreme caution when transiting after dark.` }
                    }},

                    /* ─────── NUTRITION / FEEDING RECORDS ─────── */
                    nutrition: { type: DIR, children: {
                        'feeding_schedule.txt': { type: FILE, modified: '06/11/1993 06:00', size: '1.5K', content:
`JURASSIC PARK — DAILY FEEDING SCHEDULE
Compiled by: Livestock Operations
Effective: June 1993
─────────────────────────────────────
06:00  Herbivore Morning Feed
       P02 Brachiosaur  — 400kg mixed browse
       P03 Triceratops  — 200kg cycad/fern
       P06 Stegosaurus  — 180kg low browse
       P07 Parasaur     — 150kg mixed

09:00  Carnivore Morning Feed
       P01 T-Rex        — 1 goat (live)
       P04 Dilophosaurus — 15kg chicken
       P12 Raptor       — 30kg beef (crane)
       P05 Gallimimus   — 25kg mixed

12:00  Herbivore Supplement
       ALL herbivores — Lysine supplement
       mixed into feed pellets

15:00  Carnivore Afternoon Feed
       P01 T-Rex        — 80kg beef quarters
       P12 Raptor       — 20kg beef (crane)

17:00  Compies & Small Species
       P08 Compsognathus — 10kg insects/carrion
       P09 Pteranodon    — 20kg fish

DAILY TOTALS:
  Live goats consumed:    1-2
  Beef (kg):              ~250
  Chicken (kg):           15
  Fish (kg):              20
  Browse/Fern (kg):       ~1,000
  Lysine supplements:     35 animals

Monthly Food Budget: $142,000` },

                        'lysine_contingency.txt': { type: FILE, modified: '06/01/1993 10:00', size: '1.4K', evidence: 'motive', content:
`*** TOP SECRET — INGEN EYES ONLY ***
PROJECT: LYSINE CONTINGENCY
Author: Dr. Henry Wu
Status: ACTIVE
─────────────────────────────────────
All dinosaur specimens have been engineered
with a deliberate lysine deficiency. They
cannot produce the amino acid L-lysine
endogenously.

Without regular supplementation, the animals
will slip into a coma and die within:
  - Small species:   3-5 days
  - Medium species:  5-7 days
  - Large species:   7-12 days

This is our failsafe. If the animals ever
escape the island, they cannot survive in
the wild without lysine supplementation.

HOWEVER — I have concerns:

  1. Lysine-rich plants exist on the mainland.
     Soy, beans, certain flowers are lysine-rich.
     If the animals reach a food source...

  2. The frog DNA may allow adaptation. We've
     already seen unexpected phenotype expression
     (see: Dilophosaurus venom/frill).

  3. We have NOT tested what happens when
     lysine-dependent animals breed. The
     failsafe may not propagate to offspring.

RECOMMENDATION: Do NOT rely solely on the
lysine contingency as a containment measure.

— Dr. H. Wu` }
                    }},

                    /* ─────── BREEDING / GENETICS ─────── */
                    genetics: { type: DIR, children: {
                        'breeding_report_06.log': { type: FILE, modified: '06/07/1993 10:00', size: '1.5K', evidence: 'motive', content:
`ASSET CENSUS ANOMALY — REPORT #06-93
Filed by: Census System (automated)
Reviewed by: Dr. H. Wu
─────────────────────────────────────
The automated census system has detected a
persistent count anomaly across multiple
paddocks:

EXPECTED vs ACTUAL COUNT:
  Species           Expected  Actual
  ───────────────   ────────  ──────
  T-Rex                  1       1
  Velociraptor           8       8
  Triceratops            3       4  !!
  Brachiosaurus          3       3
  Dilophosaurus          7       7
  Gallimimus            16      22  !!
  Stegosaurus            4       4
  Parasaurolophus        5       5
  Compsognathus         49      65  !!
  Pteranodon            14      14
  Herrerasaurus          3       3
  Othnielia              6       6
  ───────────────   ────────  ──────
  TOTAL               139     167

EXCESS: 28 unaccounted specimens

ANALYSIS:
  All "all-female" populations. Yet we have
  28 extra animals. Possible explanations:
  
  1. Census system error (UNLIKELY — verified)
  2. Animals are BREEDING

  West African Bullfrog (Rana goliath) DNA
  was used to fill genome gaps. This species
  is known to change sex in single-sex
  environments.

  "Life finds a way." — Dr. I. Malcolm

RECOMMENDATION: Immediate nest survey.
  
— AUTO-GENERATED REPORT —` }
                    }}
                }}
            }},

            /* ═══════════════════════════════════════════════════
               /sys/park/Shipping — DOCK & SUPPLY MANIFESTS
               (Added to existing /sys/park directory above)
               ═══════════════════════════════════════════════════ */

            /* ═══════════════════════════════════════════════════
               /log — SYSTEM AUDIT & SECURITY LOGS
               Contains: door access logs, network logs,
               system audit trails
               ═══════════════════════════════════════════════════ */
            log: { type: DIR, children: {
                'door_access_06_11.log': { type: FILE, modified: '06/12/1993 00:30', size: '1.5K', content:
`DOOR ACCESS LOG — 06/11/1993 (PARTIAL)
InGen Security — Isla Nublar
═════════════════════════════════════
22:14  Control Room       — R. ARNOLD    (badge)
22:18  Control Room       — D. NEDRY     (badge)
22:31  Server Room        — D. NEDRY     (badge)
22:45  Server Room        — D. NEDRY     (exit)
23:01  Maintenance Tunnel — D. NEDRY     (badge)
23:04  Embryo Wing Lobby  — D. NEDRY     (badge)
23:06  Embryo Cold Storage — [OVERRIDE]  <<<
23:11  Embryo Cold Storage — [EXIT]
23:15  East Dock Corridor — D. NEDRY     (badge)
23:18  East Dock Gate     — [OVERRIDE]   <<<

>>> TWO OVERRIDE EVENTS DETECTED <<<
>>> Security System: BYPASSED <<<
>>> Camera Feeds: LOOPED (7 sectors) <<<
>>> Motion Sensors: DISABLED (3 sectors) <<<

23:22  ALL DOOR LOGS      — [SYSTEM WIPE]
       >> Log recovery from backup tape <<

NOTE: Logs from 23:18 onward were deleted
by the system. This is a reconstruction from
Generator B backup. — R. Arnold` },

                'network_intrusion.log': { type: FILE, modified: '06/12/1993 01:00', size: '1.0K', evidence: 'critical', content:
`NETWORK INTRUSION DETECTION — ALERT
InGen Internal Network — Isla Nublar
═════════════════════════════════════
Timestamp: 06/11/1993 23:04:22

ALERT: Unauthorized system modification detected
Source: Terminal NEDRY-WS01 (192.168.1.15)
User: root (escalated from: nedry)

Actions performed:
  23:04:22  su root (using hardcoded password)
  23:04:25  ./whiterabbit.exe
  23:04:26  cam_loop initiated (7 sectors)
  23:04:58  motion_sensor disable (sectors 14,19,22)
  23:05:01  door_log service stopped
  23:05:03  embryo_storage unlock
  23:05:05  east_dock_gate unlock
  23:05:07  fence_shutdown scheduled (T-15:00)

SEVERITY: CRITICAL
RESPONSE: NONE (no security staff notified)

>> Intrusion detection system was running
>> but alert routing had been disabled.
>> By D. Nedry. Three months ago. — R. Arnold` },

                'system_boot.log': { type: FILE, modified: '06/12/1993 05:00', size: '0.8K', content:
`SYSTEM BOOT LOG — ISLA NUBLAR CENTRAL
═════════════════════════════════════
06/12/1993 04:47:22 — POWER RESTORED
>> Generator B online (manual start by R. Arnold)
>> Transfer time: 14.2 seconds

04:47:36 — IRIX System Boot
  Kernel: IRIX 5.3 (SGI)
  Host: jp-server
  RAM: 256MB (192MB available)
  CPU: MIPS R4400 @ 150MHz

04:47:42 — Services starting...
  [OK] sshd
  [OK] httpd
  [OK] nfsd
  [FAIL] cam_monitor — feed data corrupted
  [FAIL] fence_ctrl — waiting for main power
  [OK] census
  [FAIL] door_access — log files missing

04:48:01 — System Ready (degraded mode)

WARNING: Automated systems are operational
but fence control requires main power grid.
Backup generators do not supply sufficient
voltage for 10,000V perimeter fences.

"I hate this hacker crap." — R. Arnold` }
            }}
        }
    };

    // Navigate to a path
    function resolvePath(pathStr, root) {
        if (pathStr === '/') return root || fs;
        const base = root || fs;
        const parts = pathStr.replace(/^\//, '').replace(/\/$/, '').split('/');
        let current = base;
        for (const part of parts) {
            if (part === '..') {
                // Can't go above root in this simple VFS
                continue;
            }
            if (part === '.' || part === '') continue;
            if (!current.children || !current.children[part]) {
                return null;
            }
            current = current.children[part];
        }
        return current;
    }

    // Get absolute path parts
    function normalizePath(cwd, inputPath) {
        let parts;
        if (inputPath.startsWith('/')) {
            parts = inputPath.split('/').filter(p => p);
        } else {
            parts = [...cwd.split('/').filter(p => p), ...inputPath.split('/').filter(p => p)];
        }
        const resolved = [];
        for (const part of parts) {
            if (part === '..') resolved.pop();
            else if (part !== '.') resolved.push(part);
        }
        return '/' + resolved.join('/');
    }

    // List contents of a directory
    function listDir(node) {
        if (!node || node.type !== DIR) return null;
        return Object.entries(node.children).map(([name, child]) => ({
            name,
            type: child.type,
            modified: child.modified || '',
            size: child.size || (child.type === DIR ? '<DIR>' : '0'),
            locked: child.locked || false
        }));
    }

    // Search files for a string
    function grepFiles(searchStr, pathStr) {
        const node = resolvePath(pathStr);
        if (!node) return [];
        const results = [];
        function searchNode(n, currentPath) {
            if (n.type === FILE) {
                if (n.content && n.content.includes(searchStr)) {
                    const lines = n.content.split('\n');
                    lines.forEach((line, i) => {
                        if (line.includes(searchStr)) {
                            results.push({ file: currentPath, line: i + 1, content: line.trim() });
                        }
                    });
                }
            } else if (n.children) {
                for (const [name, child] of Object.entries(n.children)) {
                    searchNode(child, currentPath + '/' + name);
                }
            }
        }
        searchNode(node, pathStr);
        return results;
    }

    // Count all files recursively
    function countFiles(node) {
        if (!node) return 0;
        if (node.type === FILE) return 1;
        let count = 0;
        if (node.children) {
            for (const child of Object.values(node.children)) {
                count += countFiles(child);
            }
        }
        return count;
    }

    return {
        fs,
        DIR,
        FILE,
        EVIDENCE,
        resolvePath,
        normalizePath,
        listDir,
        grepFiles,
        countFiles
    };
})();
